url: https://weriselab.com/

# Site settings
title: RISE Lab
email: ffronchetti@lsu.edu
description: "Robotics and Software Engineering Laboratory (RISE) at Louisiana State University."

# Team names, titles and social links
people:
- name: Felipe Fronchetti
  pic: 3
  position: Web/Social Chair
  affiliation: Louisiana State University
  social:
    - title: twitter
      url: https://x.com/fronchat
    - title: linkedin
      url: https://www.linkedin.com/in/fronchat/
    - title: envelope
      url: mailto:fronchettl@vcu.edu


# Build settings
markdown: kramdown
permalink: pretty
